//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF244GI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.EXISTENCIAxALMACEN = new HashSet<EXISTENCIAxALMACEN>();
            this.TRANSACCION = new HashSet<TRANSACCION>();
        }
    
        public int ID_ARTICULO { get; set; }
        public string DESCRIPCION_ARTICULO { get; set; }
        public bool EXISTENCIA_ARTICULO { get; set; }
        public int ID_TIPOINVENTARIO { get; set; }
        public int COSTOUNITARIO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual TIPOINVENTARIO TIPOINVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXISTENCIAxALMACEN> EXISTENCIAxALMACEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
    }
}
