//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF244GI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXISTENCIAxALMACEN
    {
        public int ID_ARTICULO { get; set; }
        public int ID_ALMACEN { get; set; }
        public string CANTIDAD { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
