//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF244GI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionInventarioEntities : DbContext
    {
        public GestionInventarioEntities()
            : base("name=GestionInventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALMACEN> ALMACEN { get; set; }
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<EXISTENCIAxALMACEN> EXISTENCIAxALMACEN { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPOINVENTARIO> TIPOINVENTARIO { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCION { get; set; }
    }
}
