//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF244GI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public int ID_TRANSACCION { get; set; }
        public string TIPO_TRANSACCION { get; set; }
        public Nullable<int> ID_ARTICULO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string MONTO { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
